added theme
yuliiamaiboroda/admin-panel-agro pull request #51
Opened 2023-05-29 22:55 UTC by SenYaroslav

- added theme and ThemeProvider
- added some styles to PageTitle component

2023-05-30 07:38 UTC, idrahoner requested changes

2023-05-30 07:38 UTC, idrahoner commented on src/helpers/constants/theme.ts
Тема повинна містити наступні поля (скролити до Key Referece):
https://styled-system.com/theme-specification
Не всі поля обовʼязкові, але основні моменти повинні бути під такими ключами, це допоможе в майбутньому

2023-05-30 07:38 UTC, idrahoner commented on src/helpers/constants/theme.ts
https://theme-ui.com/theme-spec
Ще більше детально про темізацію, і які ключі повинні бути там, також є приклади, на які можна опиратись

2023-05-31 11:51 UTC, yuliiamaiboroda approved these changes

2023-05-31 13:07 UTC, idrahoner approved these changes

2023-05-31 13:07 UTC, merged